version: '3.4'

services:
  vrfyService:
    image: eu.gcr.io/jobrapido-sandbox/vrfy-dummy-wrap:20240115
    ports:
      - "9091:9091"
    environment:
      - SERVER_PORT=9091

  pubsub_emulator:
    image: eu.gcr.io/jobrapido-sandbox/pubsub-emulator:1.0
    ports:
      - "8085:8085"

  service:
    depends_on:
      - pubsub_emulator
    build: .
    environment:
      - SERVER_PORT=9090
      - VRFY_ENDPOINT=localhost
      - VRFY_PORT=9091
      - PUBSUB_TOPIC=test-topics
      - PUBSUB_PROJECT=test-project
      - PUBSUB_EMULATOR_HOST=localhost:8085
    ports:
      - "9090:9090"