{
 "title": "Hackathon Results",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "scenario",
    "label": "Scenario",
    "query": "SHOW TAG VALUES FROM \"grpc_req_duration\" WITH KEY = \"scenario\""
   },
   {
    "name": "run",
    "label": "run",
    "query": "SHOW TAG VALUES FROM \"grpc_req_duration\" WITH KEY = \"runName\""
   }
  ]
 },
 "panels": [
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "vus" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "vus",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Iteration Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "iterations",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "runName::tag", "operator": "=~", "value": "/^$run$/" }
     ]
    }
   ]
  },
  {
   "title": "Min Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "grpc_req_duration",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "runName::tag", "operator": "=~", "value": "/^$run$/" }
     ]
    }
   ]
  },
  {
   "title": "Max Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "grpc_req_duration",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "runName::tag", "operator": "=~", "value": "/^$run$/" }
     ]
    }
   ]
  },
  {
   "title": "Data Sent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "data_sent",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "runName::tag", "operator": "=~", "value": "/^$run$/" }
     ]
    }
   ]
  },
  {
   "title": "Avg Req Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "grpc_req_duration",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "runName::tag", "operator": "=~", "value": "/^$run$/" }
     ]
    }
   ]
  },
  {
   "title": "P90",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "grpc_req_duration",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "90" ], "type": "percentile" }
      ]
     ],
     "tags": [
      { "key": "runName::tag", "operator": "=~", "value": "/^$run$/" }
     ]
    }
   ]
  },
  {
   "title": "P95",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "grpc_req_duration",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "95" ], "type": "percentile" }
      ]
     ],
     "tags": [
      { "key": "runName::tag", "operator": "=~", "value": "/^$run$/" }
     ]
    }
   ]
  },
  {
   "title": "P99",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "grpc_req_duration",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "99" ], "type": "percentile" }
      ]
     ],
     "tags": [
      { "key": "runName::tag", "operator": "=~", "value": "/^$run$/" }
     ]
    }
   ]
  },
  { "title": "$scenario", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "scenario" },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "grpc_req_duration",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "scenario::tag", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "runName::tag", "operator": "=~", "value": "/^$run$/" }
     ]
    }
   ]
  },
  {
   "title": "Iteration Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "iterations",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "runName::tag", "operator": "=~", "value": "/^$run$/" },
      { "condition": "AND", "key": "scenario::tag", "operator": "=~", "value": "/^$scenario$/" }
     ]
    }
   ]
  },
  {
   "title": "Min Req Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "grpc_req_duration",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "runName::tag", "operator": "=~", "value": "/^$run$/" },
      { "condition": "AND", "key": "scenario::tag", "operator": "=~", "value": "/^$scenario$/" }
     ]
    }
   ]
  },
  {
   "title": "Max Req Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "grpc_req_duration",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "runName::tag", "operator": "=~", "value": "/^$run$/" },
      { "condition": "AND", "key": "scenario::tag", "operator": "=~", "value": "/^$scenario$/" }
     ]
    }
   ]
  },
  {
   "title": "Data Sent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "data_sent",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "runName::tag", "operator": "=~", "value": "/^$run$/" },
      { "condition": "AND", "key": "scenario::tag", "operator": "=~", "value": "/^$scenario$/" }
     ]
    }
   ]
  },
  {
   "title": "Avg Req Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "grpc_req_duration",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "runName::tag", "operator": "=~", "value": "/^$run$/" },
      { "condition": "AND", "key": "scenario::tag", "operator": "=~", "value": "/^$scenario$/" }
     ]
    }
   ]
  },
  {
   "title": "P90",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "grpc_req_duration",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "90" ], "type": "percentile" }
      ]
     ],
     "tags": [
      { "key": "runName::tag", "operator": "=~", "value": "/^$run$/" },
      { "condition": "AND", "key": "scenario::tag", "operator": "=~", "value": "/^$scenario$/" }
     ]
    }
   ]
  },
  {
   "title": "P95",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "grpc_req_duration",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "90" ], "type": "percentile" }
      ]
     ],
     "tags": [
      { "key": "runName::tag", "operator": "=~", "value": "/^$run$/" },
      { "condition": "AND", "key": "scenario::tag", "operator": "=~", "value": "/^$scenario$/" }
     ]
    }
   ]
  },
  {
   "title": "P99",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "grpc_req_duration",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "99" ], "type": "percentile" }
      ]
     ],
     "tags": [
      { "key": "runName::tag", "operator": "=~", "value": "/^$run$/" },
      { "condition": "AND", "key": "scenario::tag", "operator": "=~", "value": "/^$scenario$/" }
     ]
    }
   ]
  },
  {
   "title": "Successfull Checks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "measurement": "checks",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "check::tag", "operator": "=", "value": "success" },
      { "condition": "AND", "key": "runName::tag", "operator": "=~", "value": "/^$run$/" },
      { "condition": "AND", "key": "scenario::tag", "operator": "=~", "value": "/^$scenario$/" }
     ]
    }
   ]
  }
 ]
}