// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: protos/vrfy.proto

package generated

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	VrfyService_Verify_FullMethodName = "/VrfyService/Verify"
)

// VrfyServiceClient is the client API for VrfyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VrfyServiceClient interface {
	Verify(ctx context.Context, in *VrfyRequest, opts ...grpc.CallOption) (*VrfyResponse, error)
}

type vrfyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVrfyServiceClient(cc grpc.ClientConnInterface) VrfyServiceClient {
	return &vrfyServiceClient{cc}
}

func (c *vrfyServiceClient) Verify(ctx context.Context, in *VrfyRequest, opts ...grpc.CallOption) (*VrfyResponse, error) {
	out := new(VrfyResponse)
	err := c.cc.Invoke(ctx, VrfyService_Verify_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VrfyServiceServer is the server API for VrfyService service.
// All implementations must embed UnimplementedVrfyServiceServer
// for forward compatibility
type VrfyServiceServer interface {
	Verify(context.Context, *VrfyRequest) (*VrfyResponse, error)
	mustEmbedUnimplementedVrfyServiceServer()
}

// UnimplementedVrfyServiceServer must be embedded to have forward compatible implementations.
type UnimplementedVrfyServiceServer struct {
}

func (UnimplementedVrfyServiceServer) Verify(context.Context, *VrfyRequest) (*VrfyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Verify not implemented")
}
func (UnimplementedVrfyServiceServer) mustEmbedUnimplementedVrfyServiceServer() {}

// UnsafeVrfyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VrfyServiceServer will
// result in compilation errors.
type UnsafeVrfyServiceServer interface {
	mustEmbedUnimplementedVrfyServiceServer()
}

func RegisterVrfyServiceServer(s grpc.ServiceRegistrar, srv VrfyServiceServer) {
	s.RegisterService(&VrfyService_ServiceDesc, srv)
}

func _VrfyService_Verify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VrfyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VrfyServiceServer).Verify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VrfyService_Verify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VrfyServiceServer).Verify(ctx, req.(*VrfyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VrfyService_ServiceDesc is the grpc.ServiceDesc for VrfyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VrfyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "VrfyService",
	HandlerType: (*VrfyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Verify",
			Handler:    _VrfyService_Verify_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/vrfy.proto",
}
